name = "g18n"
version = "3.1.1"

description = "A comprehensive platform-agnostic internationalization library for Gleam with multi-language date/time formatting, pluralization rules, and locale-aware number formatting"
licences = ["MIT"]
repository = { type = "github", user = "renatillas", repo = "g18n" }
links = [{ title = "Website", href = "https://github.com/renatillas/g18n" }]

[documentation]
pages = [
  { title = "Changelog", path = "changelog.html", source = "./CHANGELOG.md" },
  { title = "Syntax guide", path = "syntax_guide.html", source = "./pages/syntax_guide.md" },
]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
splitter = ">= 1.1.0 and < 2.0.0"
gleam_regexp = ">= 1.1.1 and < 2.0.0"
gleam_json = ">= 3.0.0 and < 4.0.0"
trie_again = ">= 1.0.0 and < 2.0.0"
gleam_time = ">= 1.4.0 and < 2.0.0"
gleam_community_maths = ">= 2.0.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
